### ISSUE TITLE
Not all episodes have direct Listen buttons on main page for scraping

### ISSUE THREAD

**Issue by chrisjwein** [xjcl/planetmoney-rss#1]
Looking here 

http://www.npr.org/sections/money/127413729/podcast/archive?date=8-31-2017

I see that direct Listen buttons are not on every episode and that is what is scraped - does PM eventually populate those so the scraping will work?  I see that every podcast page linked from the archive does have the download tool populated so scraping there should work - might try that.

**Comment by xjcl** [comment]
You're absolutely right. I originally wrote this script before May 2017, back when all episodes had "Listen Now" buttons. Now the only play button left is the one on the episode's own page (you get there by clicking on the episode in the archive). So this broke my script.

I don't understand why they changed it as this just makes the user experience worse and in no aspect better. My guess is that it's just a new intern who doesn't know what he's doing.

As you already mentioned one possible fix would be to follow the links on the archive page to the individual episodes and scrape them in turn. However this would add a lot of downloads when running the script and more ugly scraping / case distinction in the source code.

**Comment by chrisjwein** [comment]
I patched the code to do the fetch of any podcast without a link and it only added ~10 requests on top of the minimal fetches you do already.  The scraper code you wrote correctly scrapes the individual page as well so it's a clean change at least.  I will clean it up a bit and send it over.

That said the xml file of your original is not recognized by overcast or even iOS app - will take a peek at that too.

________________________________

**Comment by chrisjwein** [comment]
[subpagepatch.zip](https://github.com/xjcl/planetmoney-rss/files/1240732/subpagepatch.zip)

Ok, you can have a look at this patch to see if you think right direction.  Since your parser works on the main and subpages the solution is somewhat elegant I think in that there is not a lot of if/else on the main/sub page.  Anyway, taking my time on this as several other projects ahead...

**Comment by xjcl** [comment]
I like that you just re-used the original parser for the "subpage" and that it actually works! Talk about writing re-usable code, haha!

I have not patched in your code but done my own modifications for the following reasons:
1. You store the subpage in `self.feed_entry['subpage']`. It makes sense to store it there, however since feed entries are directly converted into the RSS feed we will end up with a `<subpage>` tag which doesn't belong in there!
2. You first add the `new_feed_entries` and then the `new_feed_entries_missing_links` which might throw the feed entries out of order if both types are present. My solution does recursion **inside** the parser itself which IMO is the more correct approach.
3. Issues with the `pubDate`.

Interestingly my fix led to some older episodes being included in the feed now (#629, #505, #428, ..). Maybe one could write a script that guessed the episode number from the title and looked for missing ones.

I'm surprised my output is not recognized as RSS feed by Overcast or the "iOS app" (which app do you mean?). Maybe file a separate bug for that and I might look into it (I only own Androids tho).

**Comment by chrisjwein** [comment]
Yes, your changes make sense.  The key point as you say is the parser
reuse.  The iOS app is the built-in "podcast" app which I don't use - only
overcast.  I will look at the overcast issue myself sometime in the next
while.

**Comment by xjcl** [comment]
Well, I'm not entirely happy with the change as the "subpages" (episode pages) have the exact UTC datetime (with timezone offset! eg `datetime="2017-08-25T15:53:00-04:00"`) of publication which I'd like it to extract but seems to most of the time fail (so I just stuck with dates like `datetime="2017-08-25"` for now). To add an extra layer of confusion, they also have  the episode lengths in there (`datetime="P29M,9S"`). It might be better to write a separate parser for episode pages.

**Comment by xjcl** [comment]
I also noticed that the old directly scrapable episodes (ie those in my feed) were an ad-free version but the indirect ones seem to have ads XD
