### ISSUE TITLE
Clarification on discontinuation

### ISSUE THREAD

**Issue by agathazeren** [xjcl/planetmoney-rss#2]
The description of this repository says "Source got discontinued", but it is not clear what exactly the status of the repository is. There should be more clarification somewhere.

**Comment by xjcl** [comment]
Hi, thanks for your interest in my project! 

I was saying that the NPR web page where this project gets its data from is no longer updated by NPR, so it makes no sense to continue this project (I originally planned to rewrite it using BeautifulSoup and perhaps a relational database). 

I might still try to update the feed by hand by copy-pasting the XML from the official feed into it once my feed starts lagging more than 300 episodes behind, so that no episode is lost.
